---
AWSTemplateFormatVersion: '2010-09-09'

Description: 'Cloud Watch Monitoring'
Metadata:
  'AWS::CloudFormation::Interface':
    ParameterGroups:
    - Label:
        default: 'CFT CloudWatch Alert'
      Parameters:
      - EndpointId
      - Stage
    - Label:
        default: 'EC2'
      Parameters:
      - InstanceId
    - Label:
        default: 'Thresholds'
      Parameters:
      - CPUUtilizationThreshold
Parameters:
  EndpointId:
    Description: 'Cloud Watch Alert'
    Type: String
  Stage:
    Description: 'stage'
    Type: String
    Default: Test
    AllowedValues: [Test, dev]
  InstanceId:
    Description: 'The instance ID of the EC2 instance that you want to monitor.'
    Type: 'AWS::EC2::Instance::Id'
  CPUUtilizationThreshold:
    Description: 'The maximum percentage of CPU utilization.'
    Type: Number
    Default: 80
    MinValue: 0
    MaxValue: 100

Resources:
  ##########################################################################
  #                                                                        #
  #                                 TOPIC                                  #
  #                                                                        #
  ##########################################################################
  Topic:
    Type: 'AWS::SNS::Topic'
    Properties: {}
  TopicPolicy:
    Type: 'AWS::SNS::TopicPolicy'
    Properties:
      PolicyDocument:
        Id: Id1
        Version: '2012-10-17'
        Statement:
        - Sid: Sid1
          Effect: Allow
          Principal:
            AWS: '*' # Allow CloudWatch Alarms
          Action: 'sns:Publish'
          Resource: !Ref Topic
          Condition:
            StringEquals:
              'AWS:SourceOwner': !Ref 'AWS::AccountId'
      Topics:
      - !Ref Topic
  TopicEndpointSubscription:
    DependsOn: TopicPolicy
    Type: 'AWS::SNS::Subscription'
    Properties:
      DeliveryPolicy:
        healthyRetryPolicy:
          minDelayTarget: 1
          maxDelayTarget: 60
          numRetries: 100
          numNoDelayRetries: 0
          backoffFunction: exponential
        throttlePolicy:
          maxReceivesPerSecond: 1
      Endpoint: 'Anthem_IO_AWS_Linux@accenture.com'
      Protocol: email
      TopicArn: !Ref Topic
  ##########################################################################
  #                                                                        #
  #                                 ALARMS                                 #
  #                                                                        #
  ##########################################################################
  CPUUtilizationTooHighAlarm:
    DependsOn: TopicEndpointSubscription
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      AlarmActions:
      - !Ref Topic
      AlarmDescription: 'Average CPU utilization over last 10 minutes too high'
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
      - Name: InstanceId
        Value: !Ref InstanceId
      EvaluationPeriods: 1
      MetricName: CPUUtilization
      Namespace: 'AWS/EC2'
      OKActions:
      - !Ref Topic
      Period: 600
      Statistic: Average
      Threshold: !Ref CPUUtilizationThreshold
      TreatMissingData: notBreaching
  
  StatusCheckFailedAlarm:
    DependsOn: TopicEndpointSubscription
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      AlarmActions:
      - !Ref Topic
      AlarmDescription: 'EC2 instance status check or the system status check has failed'
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
      - Name: InstanceId
        Value: !Ref InstanceId
      EvaluationPeriods: 1
      MetricName: StatusCheckFailed
      Namespace: 'AWS/EC2'
      OKActions:
      - !Ref Topic
      Period: 600
      Statistic: Sum
      Threshold: 0
      TreatMissingData: notBreaching
  
#hello
Outputs:
  StackName:
    Description: 'Stack name.'
    Value: !Sub '${AWS::StackName}'
  StackTemplate:
    Description: 'Stack template.'
    Value: 'ec2-instance'
  StackVersion:
    Description: 'Stack version.'
    Value: '2.0.0'
